//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravlyk.Drawing.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ravlyk.Drawing.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Down16 {
            get {
                object obj = ResourceManager.GetObject("Down16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell size in pattern scheme.
        /// </summary>
        internal static string HintCellSize {
            get {
                return ResourceManager.GetString("HintCellSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show colored symbols.
        /// </summary>
        internal static string HintColoredSymbols {
            get {
                return ResourceManager.GetString("HintColoredSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show thread colors in cells.
        /// </summary>
        internal static string HintColors {
            get {
                return ResourceManager.GetString("HintColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show cross-stitched embroidery preview.
        /// </summary>
        internal static string HintCross {
            get {
                return ResourceManager.GetString("HintCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show black or white symbols no colored background.
        /// </summary>
        internal static string HintFullTone {
            get {
                return ResourceManager.GetString("HintFullTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show black symbols no light-colored background.
        /// </summary>
        internal static string HintHalfTone {
            get {
                return ResourceManager.GetString("HintHalfTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lines in pattern scheme.
        /// </summary>
        internal static string HintShowLines {
            get {
                return ResourceManager.GetString("HintShowLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show rulers in pattern scheme.
        /// </summary>
        internal static string HintShowRulers {
            get {
                return ResourceManager.GetString("HintShowRulers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all symbols in black color.
        /// </summary>
        internal static string HintSymbols {
            get {
                return ResourceManager.GetString("HintSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all symbols in inverted white on black color.
        /// </summary>
        internal static string HintWhiteSymbols {
            get {
                return ResourceManager.GetString("HintWhiteSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Right16 {
            get {
                object obj = ResourceManager.GetObject("Right16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeColoredSymbols_25 {
            get {
                object obj = ResourceManager.GetObject("SchemeColoredSymbols-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeColors_25 {
            get {
                object obj = ResourceManager.GetObject("SchemeColors-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeCross_25 {
            get {
                object obj = ResourceManager.GetObject("SchemeCross-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeFull_25 {
            get {
                object obj = ResourceManager.GetObject("SchemeFull-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeHalfTones_25 {
            get {
                object obj = ResourceManager.GetObject("SchemeHalfTones-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeSymbols_25 {
            get {
                object obj = ResourceManager.GetObject("SchemeSymbols-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeWhiteSymbols_25 {
            get {
                object obj = ResourceManager.GetObject("SchemeWhiteSymbols-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
