//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravlyk.SAE5.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ravlyk.SAE5.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddFile32 {
            get {
                object obj = ResourceManager.GetObject("AddFile32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Advance24 {
            get {
                object obj = ResourceManager.GetObject("Advance24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BankCard24 {
            get {
                object obj = ResourceManager.GetObject("BankCard24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bobbin24 {
            get {
                object obj = ResourceManager.GetObject("Bobbin24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detele user threads palette.
        /// </summary>
        internal static string CaptionDeletePalette {
            get {
                return ResourceManager.GetString("CaptionDeletePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checked16 {
            get {
                object obj = ResourceManager.GetObject("Checked16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checked24 {
            get {
                object obj = ResourceManager.GetObject("Checked24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checkmark24 {
            get {
                object obj = ResourceManager.GetObject("Checkmark24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Circle24 {
            get {
                object obj = ResourceManager.GetObject("Circle24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorJoin24 {
            get {
                object obj = ResourceManager.GetObject("ColorJoin24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy24 {
            get {
                object obj = ResourceManager.GetObject("Copy24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy32 {
            get {
                object obj = ResourceManager.GetObject("Copy32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cut24 {
            get {
                object obj = ResourceManager.GetObject("Cut24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete24 {
            get {
                object obj = ResourceManager.GetObject("Delete24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new thread to add to used threads palette.
        /// </summary>
        internal static string DialogHintAddNewThread {
            get {
                return ResourceManager.GetString("DialogHintAddNewThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a thread to fill cut off scheme part.
        /// </summary>
        internal static string DialogHintSelectBackgroundThread {
            get {
                return ResourceManager.GetString("DialogHintSelectBackgroundThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dice24 {
            get {
                object obj = ResourceManager.GetObject("Dice24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Door16 {
            get {
                object obj = ResourceManager.GetObject("Door16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Downloading24 {
            get {
                object obj = ResourceManager.GetObject("Downloading24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditImage100 {
            get {
                object obj = ResourceManager.GetObject("EditImage100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditImage48 {
            get {
                object obj = ResourceManager.GetObject("EditImage48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete file of selected palette..
        /// </summary>
        internal static string ErrorCannotDeletePaletteFile {
            get {
                return ResourceManager.GetString("ErrorCannotDeletePaletteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open selected file..
        /// </summary>
        internal static string ErrorCannotOpenFile {
            get {
                return ResourceManager.GetString("ErrorCannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save to selected file..
        /// </summary>
        internal static string ErrorCannotSaveFile {
            get {
                return ResourceManager.GetString("ErrorCannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot check for updates due to error: {0}.
        /// </summary>
        internal static string ErrorCheckForUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened while exporting scheme to PDF document..
        /// </summary>
        internal static string ErrorSavePdf {
            get {
                return ResourceManager.GetString("ErrorSavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened while saving pattern scheme to file..
        /// </summary>
        internal static string ErrorSaveSchema {
            get {
                return ResourceManager.GetString("ErrorSaveSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected name is already used in other threads kit palette..
        /// </summary>
        internal static string ErrorSelectedPaletteNameAlreadyUsed {
            get {
                return ResourceManager.GetString("ErrorSelectedPaletteNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file format is not supported..
        /// </summary>
        internal static string ErrorWrongFileFormat {
            get {
                return ResourceManager.GetString("ErrorWrongFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export32 {
            get {
                object obj = ResourceManager.GetObject("Export32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Facebook24 {
            get {
                object obj = ResourceManager.GetObject("Facebook24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Feedback24 {
            get {
                object obj = ResourceManager.GetObject("Feedback24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All threads palette files (*.thread, *.csv)|*.thread;*.csv.
        /// </summary>
        internal static string FileFilterAllPalettes {
            get {
                return ResourceManager.GetString("FileFilterAllPalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 2007 document (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string FileFilterExcel {
            get {
                return ResourceManager.GetString("FileFilterExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} scheme image (*.{1})|*.{1}.
        /// </summary>
        internal static string FileFilterImage {
            get {
                return ResourceManager.GetString("FileFilterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files|*.png;*.jpg;*.jpeg;*.bmp;*.gif;*.tif;*.tiff;*.sa4.
        /// </summary>
        internal static string FileFilterImages {
            get {
                return ResourceManager.GetString("FileFilterImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads palette file (*.thread)|*.thread|Comma separated values file (*.csv)|*.csv.
        /// </summary>
        internal static string FileFilterPalette {
            get {
                return ResourceManager.GetString("FileFilterPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF document (*.pdf)|*.pdf.
        /// </summary>
        internal static string FileFilterPDF {
            get {
                return ResourceManager.GetString("FileFilterPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stitch Art Easy! scheme (*.sa4)|*.sa4.
        /// </summary>
        internal static string FileFilterSAE {
            get {
                return ResourceManager.GetString("FileFilterSAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thumbnail image (*.{1})|*.{1}.
        /// </summary>
        internal static string FileFilterThumbnail {
            get {
                return ResourceManager.GetString("FileFilterThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenuName {
            get {
                return ResourceManager.GetString("FileMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving to Excel.
        /// </summary>
        internal static string FileSavingToExcel {
            get {
                return ResourceManager.GetString("FileSavingToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving scheme to Excel....
        /// </summary>
        internal static string FileSavingToExcelLabel {
            get {
                return ResourceManager.GetString("FileSavingToExcelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillColor24 {
            get {
                object obj = ResourceManager.GetObject("FillColor24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FlipHorizontal24 {
            get {
                object obj = ResourceManager.GetObject("FlipHorizontal24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FlipVertical24 {
            get {
                object obj = ResourceManager.GetObject("FlipVertical24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Globe32 {
            get {
                object obj = ResourceManager.GetObject("Globe32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hand24 {
            get {
                object obj = ResourceManager.GetObject("Hand24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open product&apos;s Facebook page.
        /// </summary>
        internal static string HintHomeButtonFacebook {
            get {
                return ResourceManager.GetString("HintHomeButtonFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new feedback email to product&apos;s support in default email application.
        /// </summary>
        internal static string HintHomeButtonFeedback {
            get {
                return ResourceManager.GetString("HintHomeButtonFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open author&apos;s professional account page on LinkedIn network.
        /// </summary>
        internal static string HintHomeButtonLinkedIn {
            get {
                return ResourceManager.GetString("HintHomeButtonLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open form to enter registration key, or get details how to buy the product.
        /// </summary>
        internal static string HintHomeButtonRegister {
            get {
                return ResourceManager.GetString("HintHomeButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open prodect&apos;s Twitter page.
        /// </summary>
        internal static string HintHomeButtonTwitter {
            get {
                return ResourceManager.GetString("HintHomeButtonTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open product&apos;s home web page in default Internet browser.
        /// </summary>
        internal static string HintHomeButtonWeb {
            get {
                return ResourceManager.GetString("HintHomeButtonWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to default values.
        /// </summary>
        internal static string HintOptionsReset {
            get {
                return ResourceManager.GetString("HintOptionsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home32 {
            get {
                object obj = ResourceManager.GetObject("Home32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home48 {
            get {
                object obj = ResourceManager.GetObject("Home48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image24 {
            get {
                object obj = ResourceManager.GetObject("Image24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageFile24 {
            get {
                object obj = ResourceManager.GetObject("ImageFile24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme properties.
        /// </summary>
        internal static string ImageInfoCaption {
            get {
                return ResourceManager.GetString("ImageInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}
        ///Size: {1}x{2} stitches
        ///Threads: {3}
        ///Colors: {4}.
        /// </summary>
        internal static string ImageInfoLabel {
            get {
                return ResourceManager.GetString("ImageInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}x{1} stitches, {2} colors.
        /// </summary>
        internal static string ImageInfoTooltip {
            get {
                return ResourceManager.GetString("ImageInfoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Import32 {
            get {
                object obj = ResourceManager.GetObject("Import32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info32 {
            get {
                object obj = ResourceManager.GetObject("Info32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to reopen this screen or restart application to update captions to new language..
        /// </summary>
        internal static string InfoRestartToChangeLanguage {
            get {
                return ResourceManager.GetString("InfoRestartToChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JPG24 {
            get {
                object obj = ResourceManager.GetObject("JPG24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Key24 {
            get {
                object obj = ResourceManager.GetObject("Key24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Key32 {
            get {
                object obj = ResourceManager.GetObject("Key32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} of {1}.
        /// </summary>
        internal static string LabelsSelectedSymbolsCount {
            get {
                return ResourceManager.GetString("LabelsSelectedSymbolsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LinkedIn24 {
            get {
                object obj = ResourceManager.GetObject("LinkedIn24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available....
        /// </summary>
        internal static string LinkLabelNewVersionAvailable {
            get {
                return ResourceManager.GetString("LinkLabelNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Palettes....
        /// </summary>
        internal static string ManagePalettes {
            get {
                return ResourceManager.GetString("ManagePalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is up to date..
        /// </summary>
        internal static string MessageNoUpdatesAvailable {
            get {
                return ResourceManager.GetString("MessageNoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads palette saved to file {0}.
        /// </summary>
        internal static string MessagePaletteSavedTo {
            get {
                return ResourceManager.GetString("MessagePaletteSavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Next24 {
            get {
                object obj = ResourceManager.GetObject("Next24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open100 {
            get {
                object obj = ResourceManager.GetObject("Open100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open16 {
            get {
                object obj = ResourceManager.GetObject("Open16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open32 {
            get {
                object obj = ResourceManager.GetObject("Open32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Page16 {
            get {
                object obj = ResourceManager.GetObject("Page16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Page32 {
            get {
                object obj = ResourceManager.GetObject("Page32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Palette24 {
            get {
                object obj = ResourceManager.GetObject("Palette24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Palette32 {
            get {
                object obj = ResourceManager.GetObject("Palette32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paste24 {
            get {
                object obj = ResourceManager.GetObject("Paste24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PDF24 {
            get {
                object obj = ResourceManager.GetObject("PDF24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PDF32 {
            get {
                object obj = ResourceManager.GetObject("PDF32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PencilTip24 {
            get {
                object obj = ResourceManager.GetObject("PencilTip24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plus24 {
            get {
                object obj = ResourceManager.GetObject("Plus24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plus32 {
            get {
                object obj = ResourceManager.GetObject("Plus32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PNG24 {
            get {
                object obj = ResourceManager.GetObject("PNG24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Preview32 {
            get {
                object obj = ResourceManager.GetObject("Preview32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Previous24 {
            get {
                object obj = ResourceManager.GetObject("Previous24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Print32 {
            get {
                object obj = ResourceManager.GetObject("Print32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Print48 {
            get {
                object obj = ResourceManager.GetObject("Print48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string PrintPageNo {
            get {
                return ResourceManager.GetString("PrintPageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string PrintPreviewZoomAuto {
            get {
                return ResourceManager.GetString("PrintPreviewZoomAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving to PDF.
        /// </summary>
        internal static string PrintSavingToPdf {
            get {
                return ResourceManager.GetString("PrintSavingToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name for new threads kit palette:.
        /// </summary>
        internal static string QueryEnterNewPaletteName {
            get {
                return ResourceManager.GetString("QueryEnterNewPaletteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want to delete selected palette?.
        /// </summary>
        internal static string QuestionDeletePalette {
            get {
                return ResourceManager.GetString("QuestionDeletePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in this scheme. Changes made in the Wizard cannot be undone with command Undo. Do you want to save the scheme before returning to Scheme Creation Wizard?.
        /// </summary>
        internal static string QuestionSaveBeforeBackToWizard {
            get {
                return ResourceManager.GetString("QuestionSaveBeforeBackToWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in this scheme. Do you want to save the scheme before closing application?.
        /// </summary>
        internal static string QuestionSaveBeforeClosing {
            get {
                return ResourceManager.GetString("QuestionSaveBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in this scheme. Do you want to save the scheme before returning to start screen?.
        /// </summary>
        internal static string QuestionSaveBeforeReturning {
            get {
                return ResourceManager.GetString("QuestionSaveBeforeReturning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in thread palettes. Do you want to save them before closing this dialog?.
        /// </summary>
        internal static string QuestionSavePalettesBeforeClosing {
            get {
                return ResourceManager.GetString("QuestionSavePalettesBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rectangle24 {
            get {
                object obj = ResourceManager.GetObject("Rectangle24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Redo24 {
            get {
                object obj = ResourceManager.GetObject("Redo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh24 {
            get {
                object obj = ResourceManager.GetObject("Refresh24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh32 {
            get {
                object obj = ResourceManager.GetObject("Refresh32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered registration data is in cancelled keys list because user had requested refund. Please use other registration details. If you believe there is an error - please contact application support..
        /// </summary>
        internal static string RegoCancelledRefundedInfo {
            get {
                return ResourceManager.GetString("RegoCancelledRefundedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered to {0}.
        /// </summary>
        internal static string RegoRegisteredTo {
            get {
                return ResourceManager.GetString("RegoRegisteredTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering Stitch Art Easy!.
        /// </summary>
        internal static string RegoThankyou {
            get {
                return ResourceManager.GetString("RegoThankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} days left of free trial period.
        /// </summary>
        internal static string RegoTrialDaysLeft {
            get {
                return ResourceManager.GetString("RegoTrialDaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial period.
        /// </summary>
        internal static string RegoTrialVersion {
            get {
                return ResourceManager.GetString("RegoTrialVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration key does not match entered User Name. Please check that both value are correct and try again..
        /// </summary>
        internal static string RegoWrongInfo {
            get {
                return ResourceManager.GetString("RegoWrongInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Return24 {
            get {
                object obj = ResourceManager.GetObject("Return24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Return32 {
            get {
                object obj = ResourceManager.GetObject("Return32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RotateLeft24 {
            get {
                object obj = ResourceManager.GetObject("RotateLeft24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RotateRight24 {
            get {
                object obj = ResourceManager.GetObject("RotateRight24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ru24 {
            get {
                object obj = ResourceManager.GetObject("Ru24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stitch Art Easy! pattern scheme document.
        /// </summary>
        internal static string SaeFileDescription {
            get {
                return ResourceManager.GetString("SaeFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save24 {
            get {
                object obj = ResourceManager.GetObject("Save24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save32 {
            get {
                object obj = ResourceManager.GetObject("Save32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save48 {
            get {
                object obj = ResourceManager.GetObject("Save48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAs24 {
            get {
                object obj = ResourceManager.GetObject("SaveAs24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveB48 {
            get {
                object obj = ResourceManager.GetObject("SaveB48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeColoredSymbols25 {
            get {
                object obj = ResourceManager.GetObject("SchemeColoredSymbols25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeColors25 {
            get {
                object obj = ResourceManager.GetObject("SchemeColors25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeCross25 {
            get {
                object obj = ResourceManager.GetObject("SchemeCross25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeFull25 {
            get {
                object obj = ResourceManager.GetObject("SchemeFull25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeHalfTones25 {
            get {
                object obj = ResourceManager.GetObject("SchemeHalfTones25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeSymbols25 {
            get {
                object obj = ResourceManager.GetObject("SchemeSymbols25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SchemeWhiteSymbols25 {
            get {
                object obj = ResourceManager.GetObject("SchemeWhiteSymbols25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Select24 {
            get {
                object obj = ResourceManager.GetObject("Select24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SoftwareBox32 {
            get {
                object obj = ResourceManager.GetObject("SoftwareBox32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Support32 {
            get {
                object obj = ResourceManager.GetObject("Support32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Title {
            get {
                object obj = ResourceManager.GetObject("Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trash24 {
            get {
                object obj = ResourceManager.GetObject("Trash24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trash32 {
            get {
                object obj = ResourceManager.GetObject("Trash32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Twitter24 {
            get {
                object obj = ResourceManager.GetObject("Twitter24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ua24 {
            get {
                object obj = ResourceManager.GetObject("Ua24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unchecked16 {
            get {
                object obj = ResourceManager.GetObject("Unchecked16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Undo24 {
            get {
                object obj = ResourceManager.GetObject("Undo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no name).
        /// </summary>
        internal static string UnsavedImageDescription {
            get {
                return ResourceManager.GetString("UnsavedImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap USA24 {
            get {
                object obj = ResourceManager.GetObject("USA24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Web24 {
            get {
                object obj = ResourceManager.GetObject("Web24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load image.
        /// </summary>
        internal static string WizardLoadImage {
            get {
                return ResourceManager.GetString("WizardLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme {0} was generated from image {1}, do you want to load it instead as source image?.
        /// </summary>
        internal static string WizardLoadSourceImageInsteadOfScheme {
            get {
                return ResourceManager.GetString("WizardLoadSourceImageInsteadOfScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Xls24 {
            get {
                object obj = ResourceManager.GetObject("Xls24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
