//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravlyk.SAE.Drawing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    public sealed partial class GridPainterSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GridPainterSettings defaultInstance = ((GridPainterSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GridPainterSettings())));
        
        public static GridPainterSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int CellSize {
            get {
                return ((int)(this["CellSize"]));
            }
            set {
                this["CellSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRulers {
            get {
                return ((bool)(this["ShowRulers"]));
            }
            set {
                this["ShowRulers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLines {
            get {
                return ((bool)(this["ShowLines"]));
            }
            set {
                this["ShowLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("176, 232, 232")]
        public global::System.Drawing.Color LineArgb {
            get {
                return ((global::System.Drawing.Color)(this["LineArgb"]));
            }
            set {
                this["LineArgb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 136, 232")]
        public global::System.Drawing.Color Line10Argb {
            get {
                return ((global::System.Drawing.Color)(this["Line10Argb"]));
            }
            set {
                this["Line10Argb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PaintMode {
            get {
                return ((string)(this["PaintMode"]));
            }
            set {
                this["PaintMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0")]
        public decimal PrintCellSize {
            get {
                return ((decimal)(this["PrintCellSize"]));
            }
            set {
                this["PrintCellSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteelBlue")]
        public global::System.Drawing.Color NumbersArgb {
            get {
                return ((global::System.Drawing.Color)(this["NumbersArgb"]));
            }
            set {
                this["NumbersArgb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("108, 184, 232")]
        public global::System.Drawing.Color Line5Argb {
            get {
                return ((global::System.Drawing.Color)(this["Line5Argb"]));
            }
            set {
                this["Line5Argb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Line10DoubleWidth {
            get {
                return ((bool)(this["Line10DoubleWidth"]));
            }
            set {
                this["Line10DoubleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PaletteOrderMode {
            get {
                return ((string)(this["PaletteOrderMode"]));
            }
            set {
                this["PaletteOrderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 255")]
        public global::System.Drawing.Color SelectionArgb1 {
            get {
                return ((global::System.Drawing.Color)(this["SelectionArgb1"]));
            }
            set {
                this["SelectionArgb1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color SelectionArgb2 {
            get {
                return ((global::System.Drawing.Color)(this["SelectionArgb2"]));
            }
            set {
                this["SelectionArgb2"] = value;
            }
        }
    }
}
