//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravlyk.SAE.Drawing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ravlyk.SAE.Drawing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value &apos;{0}&apos; in column #{1} ({2}) for color with code {3}. Value should be within 0-255..
        /// </summary>
        internal static string ErrorIncerroctPaletteCsvValue {
            get {
                return ResourceManager.GetString("ErrorIncerroctPaletteCsvValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format or number of values in CSV file. Expected list of strings in following format:.
        /// </summary>
        internal static string ErrorIncorrectPaletteCsvFormat {
            get {
                return ResourceManager.GetString("ErrorIncorrectPaletteCsvFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string ExcelSheetPalette {
            get {
                return ResourceManager.GetString("ExcelSheetPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme.
        /// </summary>
        internal static string ExcelSheetScheme {
            get {
                return ResourceManager.GetString("ExcelSheetScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string PrintColumnBlue {
            get {
                return ResourceManager.GetString("PrintColumnBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string PrintColumnCode {
            get {
                return ResourceManager.GetString("PrintColumnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string PrintColumnColor {
            get {
                return ResourceManager.GetString("PrintColumnColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stitches.
        /// </summary>
        internal static string PrintColumnCount {
            get {
                return ResourceManager.GetString("PrintColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string PrintColumnGreen {
            get {
                return ResourceManager.GetString("PrintColumnGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PrintColumnName {
            get {
                return ResourceManager.GetString("PrintColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string PrintColumnRed {
            get {
                return ResourceManager.GetString("PrintColumnRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page {0} of {1}.
        /// </summary>
        internal static string PrintPageNo {
            get {
                return ResourceManager.GetString("PrintPageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string PrintPagesIndex {
            get {
                return ResourceManager.GetString("PrintPagesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads: {0}.
        /// </summary>
        internal static string PrintThreadsName {
            get {
                return ResourceManager.GetString("PrintThreadsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add thread.
        /// </summary>
        internal static string UndoRedoActionAddThread {
            get {
                return ResourceManager.GetString("UndoRedoActionAddThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change cell color.
        /// </summary>
        internal static string UndoRedoActionChangeCellColor {
            get {
                return ResourceManager.GetString("UndoRedoActionChangeCellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change color symbol.
        /// </summary>
        internal static string UndoRedoActionChangeColorSymbol {
            get {
                return ResourceManager.GetString("UndoRedoActionChangeColorSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change thread.
        /// </summary>
        internal static string UndoRedoActionChangeThread {
            get {
                return ResourceManager.GetString("UndoRedoActionChangeThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut selection.
        /// </summary>
        internal static string UndoRedoActionCut {
            get {
                return ResourceManager.GetString("UndoRedoActionCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill region.
        /// </summary>
        internal static string UndoRedoActionFillRegion {
            get {
                return ResourceManager.GetString("UndoRedoActionFillRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string UndoRedoActionPaste {
            get {
                return ResourceManager.GetString("UndoRedoActionPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove thread.
        /// </summary>
        internal static string UndoRedoActionRemoveThread {
            get {
                return ResourceManager.GetString("UndoRedoActionRemoveThread", resourceCulture);
            }
        }
    }
}
